// ============================================================================
// PSR Platform Mock Data
// ============================================================================

import type {
  User,
  PolicyDocument,
  ConceptNote,
  CallForProposal,
  ResearchProposal,
  ResearchProject,
  AuditLog,
  Notification,
  TaxonomyItem,
  Institution,
} from "@/lib/types";

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

// ============================================================================
// Users
// ============================================================================
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@moh.gov.et",
    phone: "+251911234567",
    firstName: "Abebe",
    lastName: "Kebede",
    role: "system_admin",
    institution: "Ministry of Health",
    department: "ICT Directorate",
    position: "System Administrator",
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-03-15T08:30:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: "2",
    email: "psr@moh.gov.et",
    phone: "+251912345678",
    firstName: "Tigist",
    lastName: "Haile",
    role: "psr_officer",
    institution: "Ministry of Health",
    department: "PSR Office",
    position: "Senior Officer",
    status: "active",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    lastLogin: "2024-03-14T14:20:00Z",
    image: "https://i.pravatar.cc/150?u=2",
  },
  {
    id: "3",
    email: "researcher@aau.edu.et",
    phone: "+251913456789",
    firstName: "Dawit",
    lastName: "Mengistu",
    role: "researcher",
    institution: "Addis Ababa University",
    department: "School of Public Health",
    position: "Associate Professor",
    status: "active",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
    lastLogin: "2024-03-13T10:45:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: "4",
    email: "reviewer@moh.gov.et",
    phone: "+251914567890",
    firstName: "Sara",
    lastName: "Tesfaye",
    role: "roc_reviewer",
    institution: "Ministry of Health",
    department: "Research Oversight Committee",
    position: "Technical Reviewer",
    status: "active",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
    lastLogin: "2024-03-12T16:00:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: "5",
    email: "director@moh.gov.et",
    phone: "+251915678901",
    firstName: "Yohannes",
    lastName: "Girma",
    role: "director",
    institution: "Ministry of Health",
    department: "Policy & Planning",
    position: "Director",
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-03-15T09:00:00Z",
    image: "https://i.pravatar.cc/150?u=1", 
  },
  {
    id: "6",
    email: "leo@moh.gov.et",
    phone: "+251916789012",
    firstName: "Meron",
    lastName: "Alemu",
    role: "leo_officer",
    institution: "Ministry of Health",
    department: "LEO Office",
    position: "Learning Officer",
    status: "active",
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
    lastLogin: "2024-03-14T11:30:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: "7",
    email: "partner@who.int",
    phone: "+251917890123",
    firstName: "Michael",
    lastName: "Johnson",
    role: "institutional_partner",
    institution: "World Health Organization",
    department: "Country Office",
    position: "Health Systems Advisor",
    status: "active",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
    lastLogin: "2024-03-10T15:00:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: "8",
    email: "inactive@test.com",
    phone: "+251918901234",
    firstName: "Test",
    lastName: "User",
    role: "researcher",
    institution: "Test Institution",
    department: "Test Department",
    position: "Researcher",
    status: "inactive",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
    image: "https://i.pravatar.cc/150?u=1",
  },
];

// ============================================================================
// Concept Notes
// ============================================================================
export const mockConceptNotes: ConceptNote[] = [
  {
    id: "cn-001",
    title: "National Health Insurance Implementation Guidelines",
    background:
      "Ethiopia has embarked on implementing a national health insurance scheme to achieve universal health coverage. This concept note proposes the development of comprehensive implementation guidelines.",
    objectives:
      "To develop clear, actionable guidelines for the rollout of the national health insurance program across all regions.",
    scope:
      "The guidelines will cover enrollment procedures, benefit packages, provider payment mechanisms, and quality assurance frameworks.",
    methodology:
      "Literature review, stakeholder consultations, and pilot testing in selected woredas.",
    expectedOutcomes:
      "A comprehensive guideline document that can be used by regional health bureaus and implementing partners.",
    timeline: "Q2 2024 - Q4 2024",
    status: "under_review",
    policyType: "guideline",
    createdBy: mockUsers[1],
    attachments: [
      {
        id: "att-1",
        name: "Background_Document.pdf",
        type: "application/pdf",
        size: 2500000,
        url: "#",
        uploadedAt: "2024-03-01T00:00:00Z",
      },
    ],
    reviews: [],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "cn-002",
    title: "Digital Health Strategy 2025-2030",
    background:
      "The rapid advancement of digital technologies presents opportunities to strengthen health systems and improve health outcomes.",
    objectives:
      "To develop a comprehensive digital health strategy that aligns with national health priorities and international best practices.",
    scope:
      "Electronic health records, telemedicine, health information exchange, and digital health governance.",
    expectedOutcomes:
      "A strategic roadmap for digital health transformation in Ethiopia.",
    status: "draft",
    policyType: "strategy",
    createdBy: mockUsers[5],
    attachments: [],
    reviews: [],
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "cn-003",
    title: "Community Health Worker Training Standards",
    background:
      "Community health workers play a crucial role in primary healthcare delivery. Standardized training is essential for quality service provision.",
    objectives:
      "To establish national training standards for community health workers.",
    scope:
      "Curriculum development, competency frameworks, and certification requirements.",
    expectedOutcomes:
      "National training standards document and implementation toolkit.",
    status: "approved",
    policyType: "standard",
    createdBy: mockUsers[1],
    attachments: [],
    reviews: [
      {
        id: "rev-1",
        reviewerId: "4",
        reviewer: mockUsers[3],
        comments:
          "Well-structured concept note. Recommend proceeding to draft development.",
        recommendation: "approve",
        createdAt: "2024-02-28T00:00:00Z",
      },
    ],
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
];

// ============================================================================
// Policy Documents
// ============================================================================
export const mockPolicyDocuments: PolicyDocument[] = [
  {
    id: "pol-001",
    title: "National Health Policy 2024",
    description: "Comprehensive health policy framework for Ethiopia",
    type: "policy",
    status: "published",
    category: "Health System",
    version: 1,
    createdBy: mockUsers[4],
    assignedReviewers: [mockUsers[3], mockUsers[1]],
    currentVersion: 2,
    attachments: [
      {
        id: "att-2",
        name: "National_Health_Policy_2024.pdf",
        type: "application/pdf",
        size: 5000000,
        url: "#",
        uploadedAt: "2024-01-15T00:00:00Z",
      },
    ],
    reviews: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    publishedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "pol-002",
    title: "Primary Health Care Directive",
    description: "Directive on primary health care service delivery",
    type: "directive",
    status: "under_review",
    category: "Primary Care",
    version: 1,
    createdBy: mockUsers[1],
    assignedReviewers: [mockUsers[4]],
    currentVersion: 1,
    attachments: [],
    reviews: [],
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "pol-003",
    title: "Maternal and Child Health Protocol",
    description: "Standard protocol for maternal and child health services",
    type: "protocol",
    status: "published",
    category: "Maternal Health",
    version: 3,
    createdBy: mockUsers[1],
    assignedReviewers: [],
    currentVersion: 3,
    attachments: [],
    reviews: [],
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
    publishedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "pol-004",
    title: "Digital Health Strategy 2025-2030 Draft",
    description:
      "Strategic roadmap for digital health transformation in Ethiopia",
    type: "strategy",
    status: "under_review",
    category: "Digital Health",
    version: 1,
    createdBy: mockUsers[5],
    assignedReviewers: [mockUsers[3], mockUsers[1]],
    currentVersion: 1,
    attachments: [
      {
        id: "att-5",
        name: "DHS_Draft_v1.0.pdf",
        type: "application/pdf",
        size: 4500000,
        url: "#",
        uploadedAt: "2024-03-10T00:00:00Z",
      },
    ],
    reviews: [],
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "pol-005",
    title: "Community Health Worker Training Standards Draft",
    description:
      "National training standards document and implementation toolkit",
    type: "standard",
    status: "revision_requested",
    category: "Health Workforce",
    version: 2,
    createdBy: mockUsers[1],
    assignedReviewers: [mockUsers[4]],
    currentVersion: 2,
    attachments: [],
    reviews: [
      {
        id: "rev-2",
        reviewerId: "5",
        reviewer: mockUsers[4],
        comments: "Need more clarification on competency frameworks.",
        recommendation: "revise",
        createdAt: "2024-03-15T00:00:00Z",
      },
    ],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "pol-006",
    title: "National Health Insurance Implementation Guidelines",
    description:
      "Actionable guidelines for the rollout of the national health insurance program",
    type: "guideline",
    status: "draft",
    category: "Health Financing",
    version: 1,
    createdBy: mockUsers[1],
    assignedReviewers: [],
    currentVersion: 1,
    attachments: [],
    reviews: [],
    createdAt: "2024-03-12T00:00:00Z",
    updatedAt: "2024-03-12T00:00:00Z",
  },
  {
    id: "pol-007",
    title: "Emergency Response and Preparedness Protocol",
    description: "Standard protocol for health emergency response",
    type: "protocol",
    status: "approved",
    category: "Public Health Emergency",
    version: 1,
    createdBy: mockUsers[0],
    assignedReviewers: [mockUsers[3], mockUsers[4]],
    currentVersion: 1,
    attachments: [],
    reviews: [],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
];

// ============================================================================
// Calls for Proposals
// ============================================================================
export const mockCalls: CallForProposal[] = [
  {
    id: "call-001",
    title: "Health Systems Strengthening Research 2024",
    description:
      "Call for research proposals on health systems strengthening interventions in Ethiopia. We are seeking innovative research that addresses key challenges in health service delivery, health workforce, health financing, and health governance. This comprehensive call welcomes multidisciplinary approaches including operational research, implementation science, and systems thinking methodologies.",
    eligibilityCriteria:
      "Open to researchers affiliated with Ethiopian academic and research institutions. Principal investigators must hold at least a Master's degree. Collaborative proposals with international partners are encouraged. Organizations must be registered with the relevant authorities.",
    priorityAreas: [
      "Health System Strengthening",
      "Health Financing",
      "Health Workforce",
    ],
    budgetRange: { min: 500000, max: 2000000 },
    submissionDeadline: "2024-06-30T23:59:59Z",
    reviewDeadline: "2024-08-15T23:59:59Z",
    status: "open",
    attachments: [
      {
        id: "att-3",
        name: "Call_Guidelines.pdf",
        type: "application/pdf",
        size: 1500000,
        url: "#",
        uploadedAt: "2024-03-01T00:00:00Z",
      },
    ],
    createdBy: mockUsers[1],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
    publishedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "call-002",
    title:
      "Implementation Research on Primary Health Care Services Delivery and Community Health Worker Engagement",
    description:
      "This call invites research proposals that focus on implementation challenges and solutions for primary health care services in Ethiopia. We are particularly interested in studies examining community health worker roles, integration of digital tools, and quality of care measurement frameworks.",
    eligibilityCriteria:
      "Ethiopian institutions only. PI must have prior experience in implementation research. Minimum 3 years of research experience required. Co-investigators from international institutions welcome as supporting partners.",
    priorityAreas: [
      "Primary Health Care",
      "Implementation Research",
      "Community Health",
    ],
    budgetRange: { min: 300000, max: 1000000 },
    submissionDeadline: "2024-05-15T23:59:59Z",
    status: "open",
    attachments: [],
    createdBy: mockUsers[5],
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
    publishedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "call-003",
    title: "COVID-19 Health Systems Impact Study",
    description:
      "Research on the impact of COVID-19 on health systems and service delivery.",
    eligibilityCriteria: "Open to all researchers.",
    priorityAreas: ["Communicable Diseases", "Health System Strengthening"],
    budgetRange: { min: 200000, max: 800000 },
    submissionDeadline: "2023-12-31T23:59:59Z",
    status: "closed",
    attachments: [],
    createdBy: mockUsers[1],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    publishedAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "call-004",
    title:
      "Maternal and Neonatal Health Research Initiative: Innovations in Service Delivery and Quality Improvement",
    description:
      "This call seeks research proposals aimed at reducing maternal and neonatal mortality through innovative service delivery models, quality improvement initiatives, and evidence-based interventions. Special emphasis on approaches that strengthen referral linkages, improve skilled birth attendance, and enhance newborn care.",
    eligibilityCriteria:
      "Researchers from Ethiopian academic institutions, teaching hospitals, and health research organizations. PI with Master's degree and prior maternal health research experience preferred. Partnership with international institutions encouraged.",
    priorityAreas: [
      "Maternal Health",
      "Neonatal Health",
      "Quality Improvement",
    ],
    budgetRange: { min: 400000, max: 1500000 },
    submissionDeadline: "2024-07-31T23:59:59Z",
    status: "open",
    attachments: [
      {
        id: "att-6",
        name: "MNH_Guidelines.pdf",
        type: "application/pdf",
        size: 2000000,
        url: "#",
        uploadedAt: "2024-03-10T00:00:00Z",
      },
    ],
    createdBy: mockUsers[1],
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
    publishedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "call-005",
    title: "Non-Communicable Disease Prevention and Control Research Program",
    description:
      "Call for proposals addressing prevention, detection, and management of non-communicable diseases (NCDs) including hypertension, diabetes, cancer, and mental health conditions. Research should focus on adaptation and implementation of proven interventions in Ethiopian context.",
    eligibilityCriteria:
      "Open to researchers from all recognized research institutions in Ethiopia and regional academic centers. PI must have relevant NCD research background. Multisectoral collaboration (health, education, finance) highly encouraged.",
    priorityAreas: ["Non-Communicable Diseases", "Prevention", "Mental Health"],
    budgetRange: { min: 600000, max: 1800000 },
    submissionDeadline: "2024-08-30T23:59:59Z",
    status: "open",
    attachments: [],
    createdBy: mockUsers[5],
    createdAt: "2024-03-12T00:00:00Z",
    updatedAt: "2024-03-12T00:00:00Z",
    publishedAt: "2024-03-12T00:00:00Z",
  },
  {
    id: "call-006",
    title:
      "Health Workforce Development and Retention Strategies in Rural Areas",
    description:
      "Research targeting strategies to improve recruitment, retention, and performance of health workers in rural and remote areas of Ethiopia. Studies on task-shifting, supportive supervision, incentive mechanisms, and professional development pathways are particularly welcome.",
    eligibilityCriteria:
      "Researchers from institutions with rural health program experience. PI should have demonstrated commitment to health workforce research. Collaboration with regional health bureaus highly valued.",
    priorityAreas: ["Health Workforce", "Rural Health", "Human Resources"],
    budgetRange: { min: 450000, max: 1200000 },
    submissionDeadline: "2024-06-15T23:59:59Z",
    status: "closing_soon",
    attachments: [
      {
        id: "att-7",
        name: "HWF_Application_Form.docx",
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        size: 500000,
        url: "#",
        uploadedAt: "2024-03-08T00:00:00Z",
      },
    ],
    createdBy: mockUsers[1],
    createdAt: "2024-03-08T00:00:00Z",
    updatedAt: "2024-03-14T00:00:00Z",
    publishedAt: "2024-03-08T00:00:00Z",
  },
  {
    id: "call-007",
    title:
      "Digital Health Innovation and eHealth Solutions for Universal Health Coverage",
    description:
      "Call for innovative research and development proposals focusing on digital health technologies, electronic health records, telemedicine, mHealth applications, and health information systems to support universal health coverage in Ethiopia. Implementation research projects and digital health system evaluations welcome.",
    eligibilityCriteria:
      "Multidisciplinary teams welcomed (health professionals, engineers, data scientists). Minimum Master's level qualification for PI. Technology companies and startups may partner with research institutions. Previous digital health project experience preferred.",
    priorityAreas: [
      "Digital Health",
      "Health Information Systems",
      "Innovation",
    ],
    budgetRange: { min: 800000, max: 2500000 },
    submissionDeadline: "2024-09-30T23:59:59Z",
    status: "open",
    attachments: [],
    createdBy: mockUsers[5],
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
    publishedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "call-008",
    title:
      "Environmental Health and Communicable Disease Surveillance Research",
    description:
      "Research proposals addressing environmental determinants of health, water and sanitation-related diseases, vector-borne diseases, and strengthening communicable disease surveillance systems in Ethiopia.",
    eligibilityCriteria:
      "Researchers from Ethiopian institutions. PI with environmental health or epidemiology background. Community-based participatory research approaches encouraged.",
    priorityAreas: [
      "Environmental Health",
      "Infectious Diseases",
      "Surveillance",
    ],
    budgetRange: { min: 350000, max: 900000 },
    submissionDeadline: "2024-05-31T23:59:59Z",
    status: "open",
    attachments: [],
    createdBy: mockUsers[1],
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-03-05T00:00:00Z",
    publishedAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "call-009",
    title:
      "Capacity Building and Research Ethics: Strengthening Research Infrastructure and Institutional Capacity",
    description:
      "Research and capacity-building proposals aimed at strengthening institutional research capacity, research ethics review processes, data management systems, and promoting research culture in health institutions and universities.",
    eligibilityCriteria:
      "Institutional proposals from universities, research organizations, and health facilities. Institutional leadership and research office staff involvement required. Focus on institution-wide impact.",
    priorityAreas: [
      "Capacity Building",
      "Research Ethics",
      "Institutional Strengthening",
    ],
    budgetRange: { min: 300000, max: 1100000 },
    submissionDeadline: "2024-07-15T23:59:59Z",
    status: "open",
    attachments: [],
    createdBy: mockUsers[5],
    createdAt: "2024-03-13T00:00:00Z",
    updatedAt: "2024-03-13T00:00:00Z",
    publishedAt: "2024-03-13T00:00:00Z",
  },
  {
    id: "call-010",
    title:
      "Nutrition and Food Security Research: Addressing Malnutrition and Dietary Diversity",
    description:
      "Call for proposals targeting reduction of malnutrition in all forms, improving dietary diversity, food safety, and nutrition service delivery integration. Special focus on vulnerable populations including children, adolescents, and pregnant women.",
    eligibilityCriteria:
      "Researchers with nutrition, food science, or public health background. Institutional affiliation required. Community-level research and policy-relevant studies particularly valued.",
    priorityAreas: ["Nutrition", "Food Security", "Child Health"],
    budgetRange: { min: 400000, max: 1400000 },
    submissionDeadline: "2024-08-15T23:59:59Z",
    status: "open",
    attachments: [
      {
        id: "att-8",
        name: "Nutrition_Research_Framework.pdf",
        type: "application/pdf",
        size: 1800000,
        url: "#",
        uploadedAt: "2024-03-12T00:00:00Z",
      },
    ],
    createdBy: mockUsers[1],
    createdAt: "2024-03-12T00:00:00Z",
    updatedAt: "2024-03-12T00:00:00Z",
    publishedAt: "2024-03-12T00:00:00Z",
  },
];

// ============================================================================
// Research Proposals
// ============================================================================
export const mockProposals: ResearchProposal[] = [
  {
    id: "prop-001",
    callId: "call-001",
    call: mockCalls[0],
    title: "Strengthening District Health Management Through Digital Tools",
    abstract:
      "This study aims to evaluate the effectiveness of a digital health management information system in improving district-level health planning and decision-making.",
    background:
      "District health management teams face challenges in data-driven decision making due to fragmented information systems.",
    objectives:
      "To assess the impact of an integrated digital dashboard on health management decisions at district level.",
    methodology:
      "Mixed methods study combining quantitative analysis of health indicators with qualitative assessment of decision-making processes.",
    expectedOutcomes:
      "Evidence on the effectiveness of digital tools for health management and recommendations for scale-up.",
    ethicalConsiderations:
      "Ethical approval will be obtained from AAU IRB. Informed consent will be obtained from all participants.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [
      {
        id: "ci-1",
        name: "Helen Assefa",
        email: "helen@aau.edu.et",
        role: "co_pi",
        institution: "Addis Ababa University",
        expertise: "Health Informatics",
      },
    ],
    institution: "Addis Ababa University",
    researchArea: "Health System Strengthening",
    budget: {
      personnel: 400000,
      equipment: 150000,
      consumables: 50000,
      travel: 100000,
      other: 50000,
      total: 750000,
      justification:
        "Budget is based on 18-month implementation timeline with field work in 4 regions.",
    },
    timeline: [
      {
        id: "tl-1",
        activity: "Literature review and tool development",
        startMonth: 1,
        endMonth: 3,
        deliverables: "Digital dashboard prototype",
      },
      {
        id: "tl-2",
        activity: "Baseline data collection",
        startMonth: 4,
        endMonth: 6,
        deliverables: "Baseline report",
      },
      {
        id: "tl-3",
        activity: "Implementation and monitoring",
        startMonth: 7,
        endMonth: 15,
        deliverables: "Monthly progress reports",
      },
      {
        id: "tl-4",
        activity: "Endline evaluation and reporting",
        startMonth: 16,
        endMonth: 18,
        deliverables: "Final report and publications",
      },
    ],
    status: "under_review",
    attachments: [
      {
        id: "att-4",
        name: "Full_Proposal.pdf",
        type: "application/pdf",
        size: 3000000,
        url: "#",
        uploadedAt: "2024-03-15T00:00:00Z",
      },
    ],
    reviews: [],
    submittedAt: "2024-03-15T00:00:00Z",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "prop-002",
    callId: "call-001",
    call: mockCalls[0],
    title: "Health Financing Reform Impact Assessment",
    abstract:
      "Assessment of the impact of recent health financing reforms on service utilization and health outcomes.",
    background:
      "Ethiopia has implemented significant health financing reforms including community-based health insurance.",
    objectives:
      "To evaluate the impact of health financing reforms on access to and utilization of health services.",
    methodology:
      "Retrospective cohort study using administrative data and household surveys.",
    expectedOutcomes:
      "Evidence on reform effectiveness and policy recommendations.",
    ethicalConsiderations: "Secondary data analysis with IRB approval.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Addis Ababa University",
    researchArea: "Health Financing",
    budget: {
      personnel: 300000,
      equipment: 50000,
      consumables: 30000,
      travel: 80000,
      other: 40000,
      total: 500000,
    },
    timeline: [
      {
        id: "tl-5",
        activity: "Data collection and cleaning",
        startMonth: 1,
        endMonth: 4,
        deliverables: "Clean dataset",
      },
      {
        id: "tl-6",
        activity: "Analysis",
        startMonth: 5,
        endMonth: 10,
        deliverables: "Analysis report",
      },
      {
        id: "tl-7",
        activity: "Reporting",
        startMonth: 11,
        endMonth: 12,
        deliverables: "Final report",
      },
    ],
    status: "draft",
    attachments: [],
    reviews: [],
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "prop-003",
    callId: "call-003",
    call: mockCalls[2],
    title: "COVID-19 Impact on Essential Health Services",
    abstract:
      "Study of COVID-19 pandemic impact on essential health service delivery in Ethiopia.",
    background: "The COVID-19 pandemic disrupted health services globally.",
    objectives:
      "To quantify the impact of COVID-19 on essential health service delivery.",
    methodology: "Interrupted time series analysis of routine health data.",
    expectedOutcomes:
      "Quantified impact estimates and recovery recommendations.",
    ethicalConsiderations: "Uses anonymized routine data.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Addis Ababa University",
    researchArea: "Health System Strengthening",
    budget: {
      personnel: 250000,
      equipment: 30000,
      consumables: 20000,
      travel: 50000,
      other: 30000,
      total: 380000,
    },
    timeline: [],
    status: "completed",
    attachments: [],
    reviews: [
      {
        id: "pr-1",
        proposalId: "prop-003",
        reviewerId: "4",
        reviewer: mockUsers[3],
        technicalMerit: 22,
        methodology: 20,
        feasibility: 18,
        budget: 13,
        impact: 14,
        overallScore: 87,
        strengths: "Timely research topic with strong methodology.",
        weaknesses: "Limited geographic scope.",
        recommendation: "approve",
        comments: "Recommended for funding with minor revisions.",
        createdAt: "2023-11-15T00:00:00Z",
      },
    ],
    submittedAt: "2023-10-15T00:00:00Z",
    createdAt: "2023-10-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "prop-004",
    callId: "call-002",
    call: mockCalls[1],
    title: "Community Health Worker Motivation and Retention in Afar Region",
    abstract: "Exploration of factors influencing the motivation and retention of community health workers in pastoralist communities.",
    background: "Pastoralist regions face unique challenges in health service delivery and human resource management.",
    objectives: "To identify key motivators and barriers to retention for CHWs in the Afar region.",
    methodology: "Qualitative phenomenological study involving in-depth interviews and focus group discussions.",
    expectedOutcomes: "A framework for improving CHW retention in pastoralist settings.",
    ethicalConsiderations: "Approval from EPHI IRB. Verbal and written consent in local language.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Semera University",
    researchArea: "Health Workforce",
    budget: {
      personnel: 200000,
      equipment: 20000,
      consumables: 10000,
      travel: 150000,
      other: 20000,
      total: 400000,
    },
    timeline: [],
    status: "submitted",
    attachments: [
      {
         id: "att-prop-4-1",
         name: "Afar_CHW_Proposal.pdf",
         type: "application/pdf",
         size: 2100000,
         url: "#",
         uploadedAt: "2024-03-20T10:00:00Z"
      }
    ],
    reviews: [],
    submittedAt: "2024-03-20T10:00:00Z",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "prop-005",
    callId: "call-004",
    call: mockCalls[3],
    title: "Evaluation of Maternal Waiting Homes in Enhancing Skilled Birth Attendance",
    abstract: "A nationwide evaluation of the impact of maternal waiting homes on skilled birth attendance and neonatal outcomes.",
    background: "Maternal waiting homes have been scaled up in Ethiopia but their impact varies across regions.",
    objectives: "To evaluate the utilization and impact of maternal waiting homes on institutional delivery rates.",
    methodology: "Comparative cross-sectional study using propensity score matching.",
    expectedOutcomes: "Evidence-based recommendations for optimizing maternal waiting home services.",
    ethicalConsiderations: "Full ethical clearance from MOH IRB.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [
      {
        id: "ci-2",
        name: "Amare Tekle",
        email: "amare@ephi.gov.et",
        role: "co_pi",
        institution: "Ethiopian Public Health Institute",
        expertise: "Maternal Health"
      }
    ],
    institution: "Ethiopian Public Health Institute",
    researchArea: "Maternal & Child Health",
    budget: {
      personnel: 500000,
      equipment: 100000,
      consumables: 50000,
      travel: 200000,
      other: 50000,
      total: 900000,
    },
    timeline: [],
    status: "under_review",
    attachments: [
      {
         id: "att-prop-5-1",
         name: "MNH_Waiting_Homes.pdf",
         type: "application/pdf",
         size: 4500000,
         url: "#",
         uploadedAt: "2024-03-18T14:30:00Z"
      }
    ],
    reviews: [],
    submittedAt: "2024-03-18T14:30:00Z",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-18T14:30:00Z",
  },
  {
    id: "prop-006",
    callId: "call-005",
    call: mockCalls[4],
    title: "Integration of Mental Health Services into Primary Health Care",
    abstract: "Pilot study of an integrated mental health service delivery model at the health center level.",
    background: "Mental health services are often neglected at the primary care level despite high burden.",
    objectives: "To develop and test a feasible model for integrating depression screening and management into PHC.",
    methodology: "Stepped-wedge cluster randomized controlled trial.",
    expectedOutcomes: "Feasibility and effectiveness data on PHC-based mental health integration.",
    ethicalConsiderations: "Informed consent for patients with mental health conditions requires careful handling.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Jimma University",
    researchArea: "Non-Communicable Diseases",
    budget: {
      personnel: 600000,
      equipment: 80000,
      consumables: 40000,
      travel: 120000,
      other: 60000,
      total: 900000,
    },
    timeline: [],
    status: "submitted",
    attachments: [],
    reviews: [],
    submittedAt: "2024-03-22T09:15:00Z",
    createdAt: "2024-03-18T00:00:00Z",
    updatedAt: "2024-03-22T09:15:00Z",
  },
  {
    id: "prop-007",
    callId: "call-008",
    call: mockCalls[7],
    title: "Impact of Climate Change on Malaria Transmission in Ethiopian Highlands",
    abstract: "Investigating the shifting patterns of malaria transmission due to rising temperatures in traditionally malaria-free highlands.",
    background: "Climate change is altering the environmental suitability for malaria vectors in Ethiopia.",
    objectives: "To model the relationship between temperature changes and malaria incidence in highland areas.",
    methodology: "Ecological study using satellite-derived climate data and health facility records.",
    expectedOutcomes: "Risk maps and early warning system recommendations for highland malaria.",
    ethicalConsiderations: "Standard data privacy protocols for health records.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "University of Gondar",
    researchArea: "Communicable Diseases",
    budget: {
      personnel: 350000,
      equipment: 150000,
      consumables: 30000,
      travel: 100000,
      other: 20000,
      total: 650000,
    },
    timeline: [],
    status: "submitted",
    attachments: [
      {
         id: "att-prop-7-1",
         name: "Climate_Malaria_Full.pdf",
         type: "application/pdf",
         size: 3800000,
         url: "#",
         uploadedAt: "2024-03-21T11:45:00Z"
      }
    ],
    reviews: [],
    submittedAt: "2024-03-21T11:45:00Z",
    createdAt: "2024-03-12T00:00:00Z",
    updatedAt: "2024-03-21T11:45:00Z",
  },
  // ============================================================================
  // Approved Proposals — Ready for Funding
  // ============================================================================
  {
    id: "prop-008",
    callId: "call-001",
    call: mockCalls[0],
    title: "Task Shifting to Community Health Workers for Hypertension Management in Rural Ethiopia",
    abstract: "A cluster randomized trial evaluating the effectiveness of a task-shifting model where trained CHWs manage hypertension screening and follow-up in rural health posts.",
    background: "Non-communicable diseases, particularly hypertension, are rising rapidly in Ethiopia but specialist care is concentrated in urban areas.",
    objectives: "To evaluate whether task-shifted hypertension care by CHWs reduces blood pressure and improves medication adherence compared to standard care.",
    methodology: "Cluster randomized controlled trial across 40 health posts in Amhara and Tigray regions. Outcome measured at 12 months.",
    expectedOutcomes: "A validated, scalable CHW-based hypertension management model with cost-effectiveness data.",
    ethicalConsiderations: "EPHI IRB and Amhara Regional Health Bureau ethical approval obtained. Written informed consent from all participants.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [
      {
        id: "ci-3",
        name: "Tigist Alemu",
        email: "tigist@ju.edu.et",
        role: "co_pi",
        institution: "Jimma University",
        expertise: "Non-Communicable Diseases",
      },
    ],
    institution: "Gondar University College of Medicine",
    researchArea: "Health System Strengthening",
    budget: {
      personnel: 700000,
      equipment: 120000,
      consumables: 80000,
      travel: 250000,
      other: 50000,
      total: 1200000,
      justification: "Budget covers 24-month trial across 2 regions with 40 cluster sites.",
    },
    timeline: [
      { id: "tl-p8-1", activity: "Protocol finalization & training", startMonth: 1, endMonth: 2, deliverables: "Trained CHW cohort" },
      { id: "tl-p8-2", activity: "Baseline data collection", startMonth: 3, endMonth: 5, deliverables: "Baseline report" },
      { id: "tl-p8-3", activity: "Intervention implementation", startMonth: 6, endMonth: 18, deliverables: "Monthly progress reports" },
      { id: "tl-p8-4", activity: "Endline evaluation & reporting", startMonth: 19, endMonth: 24, deliverables: "Final report & publications" },
    ],
    status: "approved",
    attachments: [
      { id: "att-p8-1", name: "CHW_Hypertension_Proposal.pdf", type: "application/pdf", size: 5100000, url: "#", uploadedAt: "2024-02-10T00:00:00Z" },
      { id: "att-p8-2", name: "Ethical_Clearance.pdf", type: "application/pdf", size: 800000, url: "#", uploadedAt: "2024-02-15T00:00:00Z" },
    ],
    reviews: [
      {
        id: "pr-p8-1",
        proposalId: "prop-008",
        reviewerId: "4",
        reviewer: mockUsers[3],
        technicalMerit: 23,
        methodology: 22,
        feasibility: 18,
        budget: 14,
        impact: 15,
        overallScore: 92,
        strengths: "Rigorous RCT design with strong theoretical framework. Clear dissemination plan.",
        weaknesses: "High attrition risk in remote cluster sites. Mitigation strategy should be strengthened.",
        recommendation: "approve",
        comments: "Highly recommended for funding. Strong public health impact potential.",
        createdAt: "2024-03-01T00:00:00Z",
      },
    ],
    submittedAt: "2024-01-20T00:00:00Z",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "prop-009",
    callId: "call-004",
    call: mockCalls[3],
    title: "Kangaroo Mother Care Scale-Up for Low Birth Weight Neonates in Secondary Hospitals",
    abstract: "Implementation study assessing the feasibility and effectiveness of scaling Kangaroo Mother Care (KMC) to secondary-level hospitals across three Ethiopian regions.",
    background: "Ethiopia has one of the highest neonatal mortality rates globally, with low birth weight being a major contributor. KMC is proven but adoption at secondary hospitals remains low.",
    objectives: "To develop, implement and evaluate a KMC scale-up package for secondary hospitals including training, mentorship, and quality improvement components.",
    methodology: "Quasi-experimental pre-post design in 15 secondary hospitals. Process and outcome evaluation over 18 months.",
    expectedOutcomes: "Increased KMC practice rates, reduced neonatal hypothermia, and a replication guide for national scale-up.",
    ethicalConsiderations: "MOH IRB clearance obtained. Waiver for consent on anonymized routine data.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Ethiopian Public Health Institute",
    researchArea: "Maternal & Child Health",
    budget: {
      personnel: 500000,
      equipment: 200000,
      consumables: 100000,
      travel: 300000,
      other: 100000,
      total: 1200000,
    },
    timeline: [
      { id: "tl-p9-1", activity: "Baseline assessment & tool development", startMonth: 1, endMonth: 3, deliverables: "Baseline report, KMC training package" },
      { id: "tl-p9-2", activity: "Training & mentorship rollout", startMonth: 4, endMonth: 8, deliverables: "Trained hospital teams" },
      { id: "tl-p9-3", activity: "Follow-up and QI support", startMonth: 9, endMonth: 16, deliverables: "QI cycle reports" },
      { id: "tl-p9-4", activity: "Endline & knowledge products", startMonth: 17, endMonth: 18, deliverables: "Final report, replication guide" },
    ],
    status: "approved",
    attachments: [
      { id: "att-p9-1", name: "KMC_Scaleup_Proposal_v2.pdf", type: "application/pdf", size: 4300000, url: "#", uploadedAt: "2024-01-25T00:00:00Z" },
    ],
    reviews: [
      {
        id: "pr-p9-1",
        proposalId: "prop-009",
        reviewerId: "4",
        reviewer: mockUsers[3],
        technicalMerit: 21,
        methodology: 20,
        feasibility: 19,
        budget: 13,
        impact: 15,
        overallScore: 88,
        strengths: "Addresses a critical gap. Strong implementation science approach. Credible team.",
        weaknesses: "Budget for equipment is high relative to scope. Should justify each item.",
        recommendation: "approve",
        comments: "Approve with request for equipment budget justification.",
        createdAt: "2024-02-20T00:00:00Z",
      },
    ],
    submittedAt: "2024-01-18T00:00:00Z",
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-02-25T00:00:00Z",
  },
  {
    id: "prop-010",
    callId: "call-007",
    call: mockCalls[6],
    title: "mHealth Application for Real-Time Maternal Danger Sign Reporting by Community Health Extension Workers",
    abstract: "Development and pilot evaluation of an SMS and smartphone-based mHealth system enabling HEWs to report maternal danger signs and receive clinical decision support in real time.",
    background: "Delayed recognition and referral of obstetric emergencies is a key driver of maternal mortality in rural Ethiopia.",
    objectives: "To develop, pilot test and evaluate an mHealth decision-support tool for HEWs managing obstetric emergencies in low-resource settings.",
    methodology: "Mixed-methods design: iterative user-centered tool development followed by a 6-month pilot in 3 woredas.",
    expectedOutcomes: "A validated mHealth tool ready for scale-up, with evidence on acceptability, usability and impact on referral timeliness.",
    ethicalConsiderations: "AAU IRB approval. Data stored in de-identified form on secured Ethiopian Government servers.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [
      {
        id: "ci-4",
        name: "Bereket Haile",
        email: "bereket@mcit.gov.et",
        role: "researcher",
        institution: "Ministry of Innovation and Technology",
        expertise: "Digital Health Systems",
      },
    ],
    institution: "Addis Ababa University",
    researchArea: "Digital Health",
    budget: {
      personnel: 400000,
      equipment: 300000,
      consumables: 50000,
      travel: 150000,
      other: 100000,
      total: 1000000,
      justification: "Equipment costs cover smartphone procurement for HEWs and server infrastructure setup.",
    },
    timeline: [
      { id: "tl-p10-1", activity: "Needs assessment & system design", startMonth: 1, endMonth: 3, deliverables: "User requirements document, system design" },
      { id: "tl-p10-2", activity: "App development & testing", startMonth: 4, endMonth: 7, deliverables: "Beta app release" },
      { id: "tl-p10-3", activity: "Pilot implementation", startMonth: 8, endMonth: 13, deliverables: "Pilot data & monitoring reports" },
      { id: "tl-p10-4", activity: "Evaluation & documentation", startMonth: 14, endMonth: 15, deliverables: "Final report, open-source codebase" },
    ],
    status: "approved",
    attachments: [
      { id: "att-p10-1", name: "mHealth_Proposal_Final.pdf", type: "application/pdf", size: 3900000, url: "#", uploadedAt: "2024-02-05T00:00:00Z" },
      { id: "att-p10-2", name: "System_Architecture_Diagram.pdf", type: "application/pdf", size: 1200000, url: "#", uploadedAt: "2024-02-05T00:00:00Z" },
    ],
    reviews: [
      {
        id: "pr-p10-1",
        proposalId: "prop-010",
        reviewerId: "4",
        reviewer: mockUsers[3],
        technicalMerit: 22,
        methodology: 21,
        feasibility: 17,
        budget: 14,
        impact: 14,
        overallScore: 88,
        strengths: "Innovative approach addressing a real bottleneck. Strong interdisciplinary team.",
        weaknesses: "Feasibility in very low-connectivity areas needs further consideration.",
        recommendation: "approve",
        comments: "Strong innovation with clear public health relevance. Approve.",
        createdAt: "2024-03-10T00:00:00Z",
      },
    ],
    submittedAt: "2024-01-30T00:00:00Z",
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-03-12T00:00:00Z",
  },
  {
    id: "prop-011",
    callId: "call-001",
    call: mockCalls[0],
    title: "Economic Impact Analysis of Villa Developments in Bole: A Feasibility Study",
    abstract: "This study investigates the economic feasibility and market dynamics of villa developments in the Bole district of Addis Ababa, with a focus on lease terms and area utilization.",
    background: "Urban housing demand in Addis Ababa is shifting towards high-end residential units, but data on development costs and market absorption is scarce.",
    objectives: "To analyze the relationship between unit area (120sqm standard), price points (ETB 3,000/sqm), and lease duration in Bole.",
    methodology: "Market survey, cost-benefit analysis, and stakeholder interviews with developers and urban planners.",
    expectedOutcomes: "A comprehensive report on urban housing profitability and policy recommendations for affordable luxury housing.",
    ethicalConsiderations: "Standard institutional ethics approval for urban research.",
    principalInvestigator: mockUsers[2],
    coInvestigators: [],
    institution: "Addis Ababa University",
    researchArea: "Urban Development",
    budget: {
      personnel: 1500000,
      equipment: 500000,
      consumables: 200000,
      travel: 300000,
      other: 500000,
      total: 3000000,
      justification: "Budget allocated for extensive field surveys and GIS modeling.",
    },
    timeline: [],
    status: "approved",
    attachments: [],
    reviews: [],
    submittedAt: "2024-03-25T00:00:00Z",
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-03-26T00:00:00Z",
  },
];

// ============================================================================
// Research Projects (Approved & Contracted)
// ============================================================================
export const mockProjects: ResearchProject[] = [
  {
    id: "proj-001",
    proposalId: "prop-003",
    proposal: mockProposals[2],
    contractNumber: "MOH/PSR/2023/001",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    status: "active",
    milestones: [
      {
        id: "ms-1",
        title: "Inception Report",
        description: "Submit inception report with detailed workplan",
        dueDate: "2024-02-01",
        status: "completed",
        completedAt: "2024-01-28",
      },
      {
        id: "ms-2",
        title: "Data Collection Complete",
        description: "Complete all data collection activities",
        dueDate: "2024-06-30",
        status: "in_progress",
      },
      {
        id: "ms-3",
        title: "Draft Report",
        description: "Submit draft final report",
        dueDate: "2024-10-31",
        status: "pending",
      },
      {
        id: "ms-4",
        title: "Final Report",
        description: "Submit final report with all deliverables",
        dueDate: "2024-12-15",
        status: "pending",
      },
    ],
    progressReports: [
      {
        id: "pr-1",
        projectId: "proj-001",
        reportingPeriod: "Q1 2024",
        activitiesCompleted:
          "Completed literature review and finalized study protocol. Obtained ethical approval. Recruited and trained data collectors.",
        challenges: "Minor delays in ethical approval process.",
        nextSteps: "Begin data collection in selected health facilities.",
        budgetSpent: 95000,
        attachments: [],
        status: "approved",
        submittedAt: "2024-04-05T00:00:00Z",
        createdAt: "2024-04-01T00:00:00Z",
      },
    ],
    budgetUtilization: {
      allocated: 380000,
      spent: 95000,
      remaining: 285000,
      breakdown: [
        { category: "Personnel", allocated: 250000, spent: 62500 },
        { category: "Equipment", allocated: 30000, spent: 25000 },
        { category: "Consumables", allocated: 20000, spent: 3000 },
        { category: "Travel", allocated: 50000, spent: 4500 },
        { category: "Other", allocated: 30000, spent: 0 },
      ],
    },
    outputs: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-04-05T00:00:00Z",
  },
  {
    id: "proj-002",
    proposalId: "prop-011",
    proposal: mockProposals[mockProposals.length - 1],
    contractNumber: "MOE/PSR/2024/088",
    startDate: "2024-03-01",
    endDate: "2025-02-28",
    status: "at_risk",
    milestones: [
      { id: "ms-1", title: "Site Assessment", description: "Complete site assessment in Bole", dueDate: "2024-04-01", status: "completed", completedAt: "2024-03-25" },
      { id: "ms-2", title: "Preliminary Design", description: "Submit preliminary architectural designs", dueDate: "2024-07-01", status: "completed", completedAt: "2024-07-10" },
      { id: "ms-3", title: "Final Deliverable", description: "Submit Final Research Report", dueDate: "2025-02-15", status: "delayed" },
    ],
    progressReports: [
      { id: "pr-1", projectId: "proj-002", reportingPeriod: "Q1 2024", activitiesCompleted: "Initial assessment done.", challenges: "Procurement delays.", nextSteps: "Start design phase.", budgetSpent: 120000, status: "approved", submittedAt: "2024-05-10T00:00:00Z", createdAt: "2024-05-01T00:00:00Z" },
    ],
    budgetUtilization: {
      allocated: 1250000,
      spent: 450000,
      remaining: 800000,
      breakdown: [
        { category: "Personnel", allocated: 600000, spent: 300000 },
        { category: "Equipment", allocated: 200000, spent: 100000 },
        { category: "Travel", allocated: 150000, spent: 50000 },
        { category: "Other", allocated: 300000, spent: 0 },
      ],
    },
    outputs: [],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-08-10T00:00:00Z",
  },
];

// ============================================================================
// Audit Logs
// ============================================================================
export const mockAuditLogs: AuditLog[] = [
  {
    id: "log-001",
    userId: "1",
    user: mockUsers[0],
    action: "CREATE",
    entityType: "User",
    entityId: "7",
    details: { email: "partner@who.int", role: "institutional_partner" },
    ipAddress: "192.168.1.100",
    createdAt: "2024-03-01T10:30:00Z",
  },
  {
    id: "log-002",
    userId: "2",
    user: mockUsers[1],
    action: "UPDATE",
    entityType: "ConceptNote",
    entityId: "cn-001",
    details: { field: "status", from: "draft", to: "submitted" },
    ipAddress: "192.168.1.101",
    createdAt: "2024-03-10T14:20:00Z",
  },
  {
    id: "log-003",
    userId: "3",
    user: mockUsers[2],
    action: "CREATE",
    entityType: "Proposal",
    entityId: "prop-001",
    details: {
      title: "Strengthening District Health Management Through Digital Tools",
    },
    ipAddress: "192.168.1.102",
    createdAt: "2024-03-10T09:15:00Z",
  },
  {
    id: "log-004",
    userId: "4",
    user: mockUsers[3],
    action: "CREATE",
    entityType: "Review",
    entityId: "pr-1",
    details: { proposalId: "prop-003", recommendation: "approve" },
    ipAddress: "192.168.1.103",
    createdAt: "2023-11-15T16:45:00Z",
  },
  {
    id: "log-005",
    userId: "1",
    user: mockUsers[0],
    action: "UPDATE",
    entityType: "User",
    entityId: "8",
    details: { field: "status", from: "active", to: "inactive" },
    ipAddress: "192.168.1.100",
    createdAt: "2024-03-01T11:00:00Z",
  },
];

// ============================================================================
// Notifications
// ============================================================================
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "2",
    title: "New Proposal Submitted",
    message:
      'A new research proposal "Strengthening District Health Management" has been submitted for review.',
    type: "info",
    link: "/research/proposals/prop-001",
    read: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "notif-002",
    userId: "3",
    title: "Review Completed",
    message:
      'Your proposal "COVID-19 Impact on Essential Health Services" has been reviewed and approved.',
    type: "success",
    link: "/research/proposals/prop-003",
    read: true,
    createdAt: "2023-11-16T09:00:00Z",
  },
  {
    id: "notif-003",
    userId: "4",
    title: "Review Assignment",
    message: "You have been assigned to review a new research proposal.",
    type: "info",
    link: "/research/reviews",
    read: false,
    createdAt: "2024-03-16T08:30:00Z",
  },
];

// ============================================================================
// Taxonomy Items
// ============================================================================
export const mockPolicyTypes: TaxonomyItem[] = [
  {
    id: "pt-1",
    name: "Policy",
    description: "High-level policy document",
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pt-2",
    name: "Strategy",
    description: "Strategic framework or plan",
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pt-3",
    name: "Guideline",
    description: "Operational guidelines",
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pt-4",
    name: "Protocol",
    description: "Standard operating protocol",
    order: 4,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pt-5",
    name: "Standard",
    description: "Technical or quality standard",
    order: 5,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pt-6",
    name: "Directive",
    description: "Administrative directive",
    order: 6,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockResearchAreas: TaxonomyItem[] = [
  {
    id: "ra-1",
    name: "Health System Strengthening",
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-2",
    name: "Primary Health Care",
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-3",
    name: "Maternal & Child Health",
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-4",
    name: "Communicable Diseases",
    order: 4,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-5",
    name: "Non-Communicable Diseases",
    order: 5,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-6",
    name: "Health Financing",
    order: 6,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-7",
    name: "Digital Health",
    order: 7,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ra-8",
    name: "Health Workforce",
    order: 8,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockInstitutions: Institution[] = [
  {
    id: "inst-1",
    name: "Ministry of Health",
    type: "government",
    contactEmail: "info@moh.gov.et",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "inst-2",
    name: "Addis Ababa University",
    type: "academic",
    contactEmail: "info@aau.edu.et",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "inst-3",
    name: "Ethiopian Public Health Institute",
    type: "government",
    contactEmail: "info@ephi.gov.et",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "inst-4",
    name: "World Health Organization",
    type: "international",
    contactEmail: "ethiopia@who.int",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "inst-5",
    name: "USAID",
    type: "international",
    contactEmail: "ethiopia@usaid.gov",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "inst-6",
    name: "Jimma University",
    type: "academic",
    contactEmail: "info@ju.edu.et",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// ============================================================================
// Dashboard Statistics
// ============================================================================
export const mockDashboardStats = {
  admin: {
    totalUsers: mockUsers.length,
    activeUsers: mockUsers.filter((u) => u.status === "active").length,
    totalPolicies: mockPolicyDocuments.length,
    publishedPolicies: mockPolicyDocuments.filter(
      (p) => p.status === "published",
    ).length,
    totalProposals: mockProposals.length,
    activeProjects: mockProjects.filter((p) => p.status === "active").length,
    pendingReviews: 3,
    recentActivity: mockAuditLogs.slice(0, 5),
  },
  psrOfficer: {
    pendingConceptNotes: mockConceptNotes.filter(
      (cn) => cn.status === "submitted" || cn.status === "under_review",
    ).length,
    pendingDrafts: mockPolicyDocuments.filter(
      (p) => p.status === "under_review",
    ).length,
    openCalls: mockCalls.filter((c) => c.status === "open").length,
    submittedProposals: mockProposals.filter(
      (p) => p.status === "submitted" || p.status === "under_review",
    ).length,
    activeProjects: mockProjects.filter((p) => p.status === "active").length,
  },
  researcher: {
    myProposals: mockProposals.length,
    draftProposals: mockProposals.filter((p) => p.status === "draft").length,
    submittedProposals: mockProposals.filter(
      (p) => p.status === "submitted" || p.status === "under_review",
    ).length,
    activeProjects: mockProjects.length,
    openCalls: mockCalls.filter((c) => c.status === "open").length,
    upcomingDeadlines: mockCalls
      .filter((c) => c.status === "open")
      .map((c) => ({
        title: c.title,
        deadline: c.submissionDeadline,
      })),
  },
  reviewer: {
    assignedReviews: 2,
    completedReviews: 1,
    pendingReviews: 1,
  },
};
